baseURL = "https://mytop5.github.io/"
languageCode = "en-us"
title = "My Top 5"
theme = "dream"
disqusShortname = "my-top-5"

[params]
  author = "Og Maciel"
  description = "Weekly list of my Top 5 things."
  avatar = "https://avatars0.githubusercontent.com/u/53362"

  rss = true

  twitter = "OgMaciel"
  instagram = "ogmaciel"
  linkedin = "ogmaciel"
  github = "omaciel"

  siteStartYear = 2020
  enableSearch = true

  showSummaryCoverInPost = true
